baseURL = "https://libpasta.github.io/"
languageCode = "en-gb"
title = "libpasta"
theme = "hugo-theme-learn"
PygmentsCodeFences = true
PygmentsStyle = "native"
PygmentsUseClasses = true

# hugo-theme-learn config
[params]
  # Description of the site, will be used in meta information
  description = "libpasta - making passwords painless"
  # Automatically generates prev and next arrows
  autoNav = true
